set(_CATKIN_CURRENT_PACKAGE "bveeta_firmware")
set(bveeta_firmware_VERSION "0.0.0")
set(bveeta_firmware_MAINTAINER "syahmi <syahmi.bizbot@gmail.com>")
set(bveeta_firmware_PACKAGE_FORMAT "2")
set(bveeta_firmware_BUILD_DEPENDS "roscpp" "roslib" "rospy" "std_msgs")
set(bveeta_firmware_BUILD_EXPORT_DEPENDS "roscpp" "roslib" "rospy" "std_msgs")
set(bveeta_firmware_BUILDTOOL_DEPENDS "catkin")
set(bveeta_firmware_BUILDTOOL_EXPORT_DEPENDS )
set(bveeta_firmware_EXEC_DEPENDS "roscpp" "roslib" "rospy" "std_msgs")
set(bveeta_firmware_RUN_DEPENDS "roscpp" "roslib" "rospy" "std_msgs")
set(bveeta_firmware_TEST_DEPENDS )
set(bveeta_firmware_DOC_DEPENDS )
set(bveeta_firmware_URL_WEBSITE "")
set(bveeta_firmware_URL_BUGTRACKER "")
set(bveeta_firmware_URL_REPOSITORY "")
set(bveeta_firmware_DEPRECATED "")