set(_CATKIN_CURRENT_PACKAGE "bveeta_bringup")
set(bveeta_bringup_VERSION "0.0.0")
set(bveeta_bringup_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(bveeta_bringup_PACKAGE_FORMAT "2")
set(bveeta_bringup_BUILD_DEPENDS )
set(bveeta_bringup_BUILD_EXPORT_DEPENDS )
set(bveeta_bringup_BUILDTOOL_DEPENDS "catkin")
set(bveeta_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(bveeta_bringup_EXEC_DEPENDS )
set(bveeta_bringup_RUN_DEPENDS )
set(bveeta_bringup_TEST_DEPENDS )
set(bveeta_bringup_DOC_DEPENDS )
set(bveeta_bringup_URL_WEBSITE "")
set(bveeta_bringup_URL_BUGTRACKER "")
set(bveeta_bringup_URL_REPOSITORY "")
set(bveeta_bringup_DEPRECATED "")