set(_CATKIN_CURRENT_PACKAGE "bveeta_navigation")
set(bveeta_navigation_VERSION "0.0.0")
set(bveeta_navigation_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(bveeta_navigation_PACKAGE_FORMAT "2")
set(bveeta_navigation_BUILD_DEPENDS )
set(bveeta_navigation_BUILD_EXPORT_DEPENDS )
set(bveeta_navigation_BUILDTOOL_DEPENDS "catkin")
set(bveeta_navigation_BUILDTOOL_EXPORT_DEPENDS )
set(bveeta_navigation_EXEC_DEPENDS )
set(bveeta_navigation_RUN_DEPENDS )
set(bveeta_navigation_TEST_DEPENDS )
set(bveeta_navigation_DOC_DEPENDS )
set(bveeta_navigation_URL_WEBSITE "")
set(bveeta_navigation_URL_BUGTRACKER "")
set(bveeta_navigation_URL_REPOSITORY "")
set(bveeta_navigation_DEPRECATED "")