set(_CATKIN_CURRENT_PACKAGE "bveeta_control")
set(bveeta_control_VERSION "0.0.0")
set(bveeta_control_MAINTAINER "syahmi <syahmi.bizbot@gmail.com>")
set(bveeta_control_PACKAGE_FORMAT "2")
set(bveeta_control_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(bveeta_control_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(bveeta_control_BUILDTOOL_DEPENDS "catkin")
set(bveeta_control_BUILDTOOL_EXPORT_DEPENDS )
set(bveeta_control_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(bveeta_control_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(bveeta_control_TEST_DEPENDS )
set(bveeta_control_DOC_DEPENDS )
set(bveeta_control_URL_WEBSITE "")
set(bveeta_control_URL_BUGTRACKER "")
set(bveeta_control_URL_REPOSITORY "")
set(bveeta_control_DEPRECATED "")