set(_CATKIN_CURRENT_PACKAGE "bveeta_cartomapping")
set(bveeta_cartomapping_VERSION "0.0.0")
set(bveeta_cartomapping_MAINTAINER "syahmi <syahmi.bizbot@gmail.com>")
set(bveeta_cartomapping_PACKAGE_FORMAT "2")
set(bveeta_cartomapping_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(bveeta_cartomapping_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(bveeta_cartomapping_BUILDTOOL_DEPENDS "catkin")
set(bveeta_cartomapping_BUILDTOOL_EXPORT_DEPENDS )
set(bveeta_cartomapping_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "tortoisebot_navigation")
set(bveeta_cartomapping_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "tortoisebot_navigation")
set(bveeta_cartomapping_TEST_DEPENDS )
set(bveeta_cartomapping_DOC_DEPENDS )
set(bveeta_cartomapping_URL_WEBSITE "")
set(bveeta_cartomapping_URL_BUGTRACKER "")
set(bveeta_cartomapping_URL_REPOSITORY "")
set(bveeta_cartomapping_DEPRECATED "")