set(_CATKIN_CURRENT_PACKAGE "urdf_bveeta")
set(urdf_bveeta_VERSION "0.0.0")
set(urdf_bveeta_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(urdf_bveeta_PACKAGE_FORMAT "2")
set(urdf_bveeta_BUILD_DEPENDS )
set(urdf_bveeta_BUILD_EXPORT_DEPENDS )
set(urdf_bveeta_BUILDTOOL_DEPENDS "catkin")
set(urdf_bveeta_BUILDTOOL_EXPORT_DEPENDS )
set(urdf_bveeta_EXEC_DEPENDS )
set(urdf_bveeta_RUN_DEPENDS )
set(urdf_bveeta_TEST_DEPENDS )
set(urdf_bveeta_DOC_DEPENDS )
set(urdf_bveeta_URL_WEBSITE "")
set(urdf_bveeta_URL_BUGTRACKER "")
set(urdf_bveeta_URL_REPOSITORY "")
set(urdf_bveeta_DEPRECATED "")