set(_CATKIN_CURRENT_PACKAGE "bveeta_gazebo")
set(bveeta_gazebo_VERSION "0.0.0")
set(bveeta_gazebo_MAINTAINER "syahmi <syahmi.bizbot@gmail.com>")
set(bveeta_gazebo_PACKAGE_FORMAT "2")
set(bveeta_gazebo_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "system_lib" "gazebo_ros")
set(bveeta_gazebo_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "gazebo_ros")
set(bveeta_gazebo_BUILDTOOL_DEPENDS "catkin")
set(bveeta_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(bveeta_gazebo_EXEC_DEPENDS "gazebo" "roscpp" "rospy" "std_msgs" "system_lib" "tortoisebot_description" "gazebo_ros")
set(bveeta_gazebo_RUN_DEPENDS "gazebo" "roscpp" "rospy" "std_msgs" "system_lib" "tortoisebot_description" "gazebo_ros")
set(bveeta_gazebo_TEST_DEPENDS )
set(bveeta_gazebo_DOC_DEPENDS )
set(bveeta_gazebo_URL_WEBSITE "")
set(bveeta_gazebo_URL_BUGTRACKER "")
set(bveeta_gazebo_URL_REPOSITORY "")
set(bveeta_gazebo_DEPRECATED "")