set(_CATKIN_CURRENT_PACKAGE "bveeta_description")
set(bveeta_description_VERSION "0.0.0")
set(bveeta_description_MAINTAINER "syahmi <syahmi.bizbot@gmail.com>")
set(bveeta_description_PACKAGE_FORMAT "2")
set(bveeta_description_BUILD_DEPENDS "rospy")
set(bveeta_description_BUILD_EXPORT_DEPENDS "rospy")
set(bveeta_description_BUILDTOOL_DEPENDS "catkin")
set(bveeta_description_BUILDTOOL_EXPORT_DEPENDS )
set(bveeta_description_EXEC_DEPENDS "rospy")
set(bveeta_description_RUN_DEPENDS "rospy")
set(bveeta_description_TEST_DEPENDS )
set(bveeta_description_DOC_DEPENDS )
set(bveeta_description_URL_WEBSITE "")
set(bveeta_description_URL_BUGTRACKER "")
set(bveeta_description_URL_REPOSITORY "")
set(bveeta_description_DEPRECATED "")