set(_CATKIN_CURRENT_PACKAGE "hectormapping")
set(hectormapping_VERSION "0.0.0")
set(hectormapping_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(hectormapping_PACKAGE_FORMAT "2")
set(hectormapping_BUILD_DEPENDS )
set(hectormapping_BUILD_EXPORT_DEPENDS )
set(hectormapping_BUILDTOOL_DEPENDS "catkin")
set(hectormapping_BUILDTOOL_EXPORT_DEPENDS )
set(hectormapping_EXEC_DEPENDS )
set(hectormapping_RUN_DEPENDS )
set(hectormapping_TEST_DEPENDS )
set(hectormapping_DOC_DEPENDS )
set(hectormapping_URL_WEBSITE "")
set(hectormapping_URL_BUGTRACKER "")
set(hectormapping_URL_REPOSITORY "")
set(hectormapping_DEPRECATED "")