set(_CATKIN_CURRENT_PACKAGE "bveeta_cartonavigation")
set(bveeta_cartonavigation_VERSION "0.0.0")
set(bveeta_cartonavigation_MAINTAINER "syahmi <syahmi.bizbot@gmail.com>")
set(bveeta_cartonavigation_PACKAGE_FORMAT "2")
set(bveeta_cartonavigation_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(bveeta_cartonavigation_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(bveeta_cartonavigation_BUILDTOOL_DEPENDS "catkin")
set(bveeta_cartonavigation_BUILDTOOL_EXPORT_DEPENDS )
set(bveeta_cartonavigation_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(bveeta_cartonavigation_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(bveeta_cartonavigation_TEST_DEPENDS )
set(bveeta_cartonavigation_DOC_DEPENDS )
set(bveeta_cartonavigation_URL_WEBSITE "")
set(bveeta_cartonavigation_URL_BUGTRACKER "")
set(bveeta_cartonavigation_URL_REPOSITORY "")
set(bveeta_cartonavigation_DEPRECATED "")